Friend Module DataSources

    Friend ReadOnly years As String() =
        {
            "all",
            "1937",
            "1947",
            "1949",
            "1950",
            "1952",
            "1953",
            "1954",
            "1955",
            "1956",
            "1957",
            "1958",
            "1959",
            "1960",
            "1961",
            "1962",
            "1963",
            "1964",
            "1965",
            "1966",
            "1967",
            "1968",
            "1969",
            "1970",
            "1971",
            "1972",
            "1973",
            "1974",
            "1975",
            "1976",
            "1977",
            "1978",
            "1979",
            "1980",
            "1981",
            "1982",
            "1983",
            "1984",
            "1985",
            "1986",
            "1987",
            "1988",
            "1989",
            "1990",
            "1991",
            "1992",
            "1993",
            "1994",
            "1995",
            "1996",
            "1997",
            "1998",
            "1999",
            "2000",
            "2001",
            "2002",
            "2003",
            "2004",
            "2005",
            "2006",
            "2007",
            "2008",
            "2009",
            "2010",
            "2011",
            "2012",
            "2013",
            "2014",
            "2015",
            "2016",
            "2017",
            "2018"
    }

    Friend ReadOnly genres As String() =
        {
            "all",
            "AOR",
            "Acid rock",
            "Alternative metal",
            "Alternative rock",
            "Ambient black metal",
            "Anarcho-punk",
            "Art punk",
            "Art rock",
            "Atmospheric black metal",
            "Atmospheric metal",
            "Atmospheric sludge metal",
            "Avant-garde",
            "Avant-garde metal",
            "Beatdown",
            "Black metal",
            "Blackened death metal",
            "Blues-rock",
            "Britpop rock",
            "Brutal death metal",
            "Cello metal",
            "Cello rock",
            "Celtic metal",
            "Christian punk",
            "Christian rock",
            "Classic rock",
            "College rock",
            "Country rock",
            "Crossover thrash",
            "Crust punk",
            "Dark Wave",
            "Dark metal",
            "Death metal",
            "Deathcore",
            "Desert rock",
            "Detroit rock",
            "Doom metal",
            "Dream pop",
            "Drone metal",
            "Electronic rock",
            "Emo",
            "Epic metal",
            "Experimental rock",
            "Extreme metal",
            "Female Band",
            "Female Vocal",
            "Folk metal",
            "Folk rock",
            "Funeral doom",
            "Funk metal",
            "Funk rock",
            "Garage punk",
            "Garage rock",
            "Geek rock",
            "Glam metal",
            "Glam punk",
            "Glam rock",
            "Goregrind",
            "Gothic metal",
            "Gothic rock",
            "Grindcore",
            "Groove metal",
            "Group Sounds",
            "Grunge",
            "Hard rock",
            "Hardcore",
            "Hardcore punk",
            "Heartland rock",
            "Heavy metal",
            "Horror metal",
            "Horror punk",
            "Indie pop",
            "Indie rock",
            "Industrial metal",
            "Industrial rock",
            "Instrumental rock",
            "Jam band",
            "Jangle pop",
            "Jazz Fusion",
            "Krautrock",
            "Math rock",
            "Mathcore",
            "Medieval metal",
            "Melodic Hard Rock",
            "Melodic Heavy",
            "Melodic Power",
            "Melodic Rock",
            "Melodic black metal",
            "Melodic death metal",
            "Melodic metal",
            "Melodic viking metal",
            "Metalcore",
            "NWOBHM",
            "Nazi punk",
            "Neo-classical metal",
            "Neo-progressive rock",
            "Neofolk",
            "New Wave",
            "Noise pop",
            "Noise rock",
            "Nu metal",
            "Oi!",
            "Oriental Metal",
            "Pagan metal",
            "Paisley Underground",
            "Pop metal",
            "Pop rock",
            "Post Grunge",
            "Post-hardcore",
            "Post-metal",
            "Post-punk",
            "Post-rock",
            "Power metal",
            "Power pop",
            "Progressive metal",
            "Progressive rock",
            "Protopunk",
            "Psychedelic black metal",
            "Psychedelic rock",
            "Pub rock",
            "Punk-rock",
            "Rap metal",
            "Rap rock",
            "Rapcore",
            "Raw black metal",
            "Riot Grrrl",
            "Rock and roll",
            "Rockabilly",
            "Roots rock",
            "Shoegazing",
            "Ska Punk",
            "Skate punk",
            "Sleaze  Rock",
            "Sludge metal",
            "Soft rock",
            "Southern rock",
            "Space rock",
            "Speed metal",
            "Stoner metal",
            "Stoner sludge metal",
            "Surf",
            "Symphonic black metal",
            "Symphonic gothic metal",
            "Symphonic metal",
            "Symphonic power metal",
            "Symphonic rock",
            "Technical death metal",
            "Thrash metal",
            "Traditional metal",
            "Traditional/Southern sludge metal",
            "Twee pop",
            "Viking black metal",
            "Viking metal"
    }

    Friend ReadOnly countries As String() =
        {
            "all",
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia-Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, D.R.",
            "Cook Islands",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curacao",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe (French)",
            "Guam (USA)",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea Bissau",
            "Guyana",
            "Haiti",
            "Holy See",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "International",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Ivory Coast (Cote D`Ivoire)",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique (French)",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia (French)",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "North Korea",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn Island",
            "Poland",
            "Polynesia (French)",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Pierre and Miquelon",
            "Saint Vincent and Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen Islands",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Tasmania",
            "Thailand",
            "Timor-Leste (East Timor)",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Vietnam",
            "Virgin Islands",
            "Wallis and Futuna Islands",
            "Yemen",
            "Zaire",
            "Zambia",
            "Zimbabwe"
    }

End Module
